include conf/distro/include/fsl-imx-base.inc
require conf/distro/b2qt.conf

DISTRO = "ezurio-b2qt"
DISTRO_NAME = "Ezurio b2qt"
DISTRO_FEATURES:append = " wayland "

# Need to override setting in meta-boot2qt layer (fsl.inc) to use boundary u-boot and kernel
IMX_DEFAULT_BOOTLOADER:imx-nxp-bsp = "u-boot-boundary"
PREFERRED_PROVIDER_virtual/kernel:imx-nxp-bsp = "linux-boundary"

PREFERRED_PROVIDER_networkmanager = "summit-networkmanager"
PREFERRED_RPROVIDER_networkmanager = "summit-networkmanager"
PREFERRED_RPROVIDER_networkmanager-nmcli = "summit-networkmanager"
PREFERRED_RPROVIDER_wireless-regdb-static = "wireless-regdb"
PREFERRED_PROVIDER_wpa-supplicant = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant-cli = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant-passphrase = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant-lib = "summit-supplicant"

IMAGE_FSTYPES += " wic.gz"

MACHINE_USES_VIVANTE_KERNEL_DRIVER_MODULE = "1"

QT_QPA_PLATFORM = "wayland-egl"
