# i.MX DISTRO for Wayland with X11

include conf/distro/include/fsl-imx-base.inc
include conf/distro/include/fsl-imx-preferred-env.inc

DISTRO = "fsl-imx-xwayland-boundary"

# Remove conflicting backends
DISTRO_FEATURES:remove = "directfb "
DISTRO_FEATURES:append = " x11 wayland pam"

PREFERRED_PROVIDER_virtual/kernel:imx-nxp-bsp = "linux-boundary"
PREFERRED_PROVIDER_virtual/bootloader:imx-nxp-bsp = "u-boot-boundary"

PREFERRED_RPROVIDER_networkmanager = "summit-networkmanager"
PREFERRED_RPROVIDER_networkmanager-nmcli = "summit-networkmanager"
PREFERRED_RPROVIDER_wireless-regdb-static = "wireless-regdb"
PREFERRED_RPROVIDER_wpa-supplicant = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant-cli = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant-passphrase = "summit-supplicant"

IMAGE_FSTYPES += " wic.gz wic.sparse"
IMAGE_CLASSES += " image_types_sparse"


MACHINE_USES_VIVANTE_KERNEL_DRIVER_MODULE = "1"

# Route the 3D graphics routing engine back to NXP's Vivante stack for i.MX8MQ
PREFERRED_PROVIDER_virtual/egl:mx8mq-nxp-bsp = "imx-gpu-viv"
PREFERRED_PROVIDER_virtual/libgles1:mx8mq-nxp-bsp = "imx-gpu-viv"
PREFERRED_PROVIDER_virtual/libgles2:mx8mq-nxp-bsp = "imx-gpu-viv"
PREFERRED_PROVIDER_virtual/libgles3:mx8mq-nxp-bsp = "imx-gpu-viv"
PREFERRED_PROVIDER_virtual/libgbm:mx8mq-nxp-bsp = "imx-gpu-viv"
PREFERRED_PROVIDER_virtual/mesa:mx8mq-nxp-bsp = "mesa-gl"
CORE_IMAGE_EXTRA_INSTALL:append:mx8mq-nxp-bsp = " imx-gpu-viv imx-gpu-viv-tools"
